blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('apply/', views.apply, name='apply'),
    path('test/', views.test, name='test'),
    path('home/<str:username>/', views.index, name='index'),
    path('home/<str:username>/article/', views.user_article, name='article'),
    path('article/<int:aid>', views.article_detail, name='article'),
]

justfly/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls')),
    path('blog/', include('blog.urls')),
]

web/urls.py
from django.urls import path

from . import views

app_name = 'web'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('signin/checkusername/', views.checkusername, name='checkusername'),
    path('signout/', views.signout, name='signout'),
    path('upload_image/', views.upload_image, name='upload_image'),
    path('captcha/', views.handle_captcha, name='captcha'),
    path('<str:username>/', views.homepage, name='homepage'),
]

web/templates/web/applyblog.html
{% extends "web/extends/index.html" %}

{% block title %}
Apply blog -Just fly
{% endblock %}

{% block mainbody %}
<div class="container">
        <!-- novalidate关闭html5自带的验证 -->
        <form action="{% url "apply-blog" %}" method="post" novalidate>
            {% csrf_token %}
            <p></p>
            <div class="form-group">
                <label class="cus-label">{{ form.title.label }}</label>
                <small class="text-muted">{{ form.title.help_text }}</small>
                {{ form.title }}
                <small class="form-text text-danger user-error">{{ form.title.errors.0 }}</small>
            </div>
            <div class="form-group">
                <label class="cus-label">{{ form.summary.label }}</label>
                <small class="text-muted">{{ form.summary.help_text }}</small>
                {{ form.summary }}
                <small class="form-text text-danger">{{ form.summary.errors.0 }}</small>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

web/templates/web/homepage.html
{% extends "web/extends/index.html" %}

{% block title %}
    {{ user_info.username }}'s blog
{% endblock %}

{% block mainbody %}
    <div class="jumbotron bg-info">
        <h1 class="display-4">{{ user_info.nickname }}</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url "blog:apply" %}" role="button">Apply for your blog</a>
        </p>
    </div>
{% endblock %}

web/templates/web/index.html
{% extends "web/extends/index.html" %}

web/templates/web/signin.html
{% extends "web/extends/index.html" %}

{% block heraderarea %}
    {{ block.super }}
    <style>
        .cus-label {
            font-size: large;
            font-family: bold;
        }
        .captcha {
            width: 120px;
            height: 46px;
            cursor: pointer;
        }
    </style>
{% endblock %}


{% block mainbody %}
    <div class="container">
        <form action="{% url "web:signin" %}" method="post">
            {% csrf_token %}
            <p></p>
            <div class="form-group">
                <label class="cus-label">Username</label>
                {% if request.POST %}
                    <input type="text" class="form-control" placeholder="Enter username" name="username" value="{{ request.POST.username }}">
                {% else %}
                    <input type="text" class="form-control" placeholder="Enter username" name="username" onchange="checkUsername(this);">
                {% endif %}
                <small class="form-text text-danger user-error">{{ errors.username }}</small>
            </div>
            <div class="form-group">
                <label class="cus-label">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
                <small class="form-text text-danger">{{ errors.password }}</small>
            </div>
            <div class="form-row">
                <div class="col">
                    <label class="cus-label">Captcha</label>
                    <small class="text-muted">Click the captcha to change another.</small>
                    <input type="text" class="form-control" placeholder="Enter captcha" name="captcha">
                    <small class="form-text text-danger">{{ errors.captcha }}</small>
                </div>
            <div class="col">
                <br>
                <img src="{% url "web:captcha" %}" onclick="changeCaptcha(this);" alt="" class="captcha"/>
            </div>
            </div>
            <br>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1" name="nosignin1month">
                <label class="form-check-label" for="exampleCheck1">一个月内免登录</label>
            </div>
            <button type="submit" class="btn btn-primary">提交</button>
        </form>
    </div>
<script>
    {% load staticfiles %}
    {% include "web/include/ajaxcsrf.js" %}
    {% include "web/include/sign.js" %}
</script>

{% endblock %}

web/templates/web/signup.html
{% extends "web/extends/index.html" %}

{% block heraderarea %}
    {{ block.super }}
    <style>
        .cus-label {
            font-size: large;
            font-family: bold;
        }
        .captcha {
            width: 120px;
            height: 46px;
            cursor: pointer;
        }
    </style>
{% endblock %}


{% block mainbody %}
    <div class="container">
        <!-- novalidate关闭html5自带的验证 -->
        <form action="{% url "web:signup" %}" method="post" novalidate>
            {% csrf_token %}
            <p></p>
            <div class="form-group">
                <label class="cus-label">{{ form.username.label }}</label>
                <small class="text-muted">Username can just contains integer or letter or _</small>
                {{ form.username }}
                <small class="form-text text-danger user-error">{{ form.username.errors.0 }}</small>
            </div>
            <label class="cus-label">{{ form.image.label }}</label>
            <div class="custom-file">
                {{ form.image }}
                <label class="custom-file-label" for="customFile">Choose an avatar</label>
            </div>
            <p></p>
            <div class="form-group">
                <label class="cus-label">{{ form.email.label }}</label>
                <small class="text-muted">We'll never share your email with anyone else.</small>
                {{ form.email }}
                <small class="form-text text-danger">{{ form.email.errors.0 }}</small>
            </div>
            <div class="form-group">
                <label class="cus-label">{{ form.password.label }}</label>
                {{ form.password }}
                <small class="form-text text-danger">{{ form.password.errors.0 }}</small>
            </div>
            <div class="form-row">
                <div class="col">
                    <label class="cus-label">{{ form.captcha.label }}</label>
                    <small class="text-muted">Click the captcha to change another.</small>
                    {{ form.captcha }}
                    <small class="form-text text-danger">{{ form.captcha.errors.0 }}</small>
                </div>
            <div class="col">
                <br>
                <img src="{% url "web:captcha" %}" onclick="changeCaptcha(this);" alt="" class="captcha"/>
            </div>
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>


{#图片预览 暂不考虑#}
{#    <div class="container">#}
{#        <h3>文件上传</h3>#}
{#        <iframe style="display: none;" id="iframe" name="ifra"></iframe>#}
{#        <form id="fm" action="/web/upload_image/" method="POST" enctype="multipart/form-data" target="ifra">#}
{#            {% csrf_token %}#}
{#            <input type="file" name="img" onchange="uploadFiles();" />#}
{#        </form>#}
{##}
{#        <h3>预览</h3>#}
{#        <div id="preview"></div>#}
{#    </div>#}
<script>
{#    function uploadFiles() {#}
{#        // 绑定onload属性#}
{#        document.getElementById('iframe').onload = reloadIframe;#}
{#        // 提交#}
{#        document.getElementById('fm').submit();#}
{#    }#}
{##}
{#    function reloadIframe() {#}
{#        var content = this.contentWindow.document.body.innerHTML;#}
{#        var obj = JSON.parse(content);#}
{#        // 创建img标签#}
{#        var tag = document.createElement('img');#}
{#        tag.src = obj.data;#}
{#        tag.className = 'img-thumbnail';#}
{#        // 注意需先清空再添加，否则会导致div标签中出现多个img标签，使得上传与预览不一致#}
{#        $('#preview').empty().append(tag);#}
{#    }#}
{##}
{% load staticfiles %}
{% include "web/include/ajaxcsrf.js" %}
{% include "web/include/sign.js" %}
</script>

{% endblock %}